version: '3.3'
services:
  byf:
    build: ./
    ports:
      - 8000:8080
    environment:
      - SPRING_PROFILES_ACTIVE = container
      - SPRING_DATASOURCE_URL = jdbc:mysql://mysql_db:3300/BYF?useSSL=false&serverTimezone=Europe/Warsaw&verifyServerCertificate=false&autoReconnect=true&useSSL=false
    restart: always
    depends_on:
      - database
  database:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BYF
      MYSQL_USER: user
    ports:
      - 3300:3306
    restart: always
