version: '3.3'
services:
  byf:
    build: ./
    ports:
      - "8080:10101"
    environment:
      - SPRING_DATASOURCE_URL = jdbc:mysql://database:3306/BYF?useSSL=false&serverTimezone=UTC
    depends_on:
      - database
  database:
    container_name: 'database'
    image: mysql
    environment:
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BYF
      MYSQL_USER: user
    ports:
      - "3306:3306"
    restart: always
